// Styles
import '@/index.css';

import { generateMetadata } from '../utils/seo';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { PropsWithChildren } from 'react';

/**
 * Global metadata configuration for the entire site.
 * Generated by utility function for consistency and reusability.
 */
export const metadata = generateMetadata({ isRootLayout: true });

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <div id="root">
          <Header />

          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
