import { generateMetadata } from "../utils/seo";

/**
 * Global metadata configuration for the entire site.
 * Generated by utility function for consistency and reusability.
 */
export const metadata = generateMetadata({ isRootLayout: true });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div id="root">{children}</div>
      </body>
    </html>
  );
}
