// Styles
import '@/styles/globals.scss';

import { ClerkProvider } from '@clerk/nextjs';
import { generateMetadata } from '@/lib/seo';
import ClerkAuthBridge from '@/components/ClerkAuthBridge';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { CLERK_APPEARANCE } from '@/lib/clerk';
import { PropsWithChildren } from 'react';
import type { Viewport } from 'next';

/**
 * Global metadata configuration for the entire site.
 * Generated by utility function for consistency and reusability.
 */
export const metadata = generateMetadata({ isRootLayout: true });

/**
 * Disables pinch- and double-tap-zoom at the viewport level, since the game
 * ships its own in-app zoom.
 *
 * Note: iOS Safari ignores `maximumScale` and `userScalable` for accessibility
 * reasons, so this does nothing there — including for the "drag to select"
 * magnifier that a tap → release → press-and-hold sequence triggers. That
 * gesture is suppressed by `useBoardTouchDefaultSuppression` instead.
 */
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <ClerkProvider appearance={CLERK_APPEARANCE}>
      <html lang="en">
        <body>
          <div id="root">
            <ClerkAuthBridge />
            <Header />

            {children}

            <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
